services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared_portainer
    command: tunnel --no-autoupdate run --token ${CLOUDFLARED_TOKEN}
    restart: unless-stopped
    networks:
      - frontend

networks:
  frontend:
    name: "frontend"
    external: true
