route:
  receiver: "discord-notifications"
receivers:
  - name: "discord-notifications"
    webhook_configs:
      - url: "https://discord.com/api/webhooks/1389968002841055333/-vkjUf_kPdu2giOiAA_bilExx_1PRQGioDg19tH2Q9uEBJ8-9E9hbCbfRWTuLdwAdCNu"
