services:
  prometheus:
    image: prom/prometheus:v3.4.2
    container_name: prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.retention.time=15d
      - --storage.tsdb.retention.size=10GB
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9090/-/healthy || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - microservices-net

  loki:
    image: grafana/loki:3.5.1
    container_name: loki
    command: -config.file=/etc/loki/local-config.yml
    ports:
      - "3100:3100"
    volumes:
      - ./loki/loki-local-config.yml:/etc/loki/local-config.yml:ro
      - loki-data:/loki
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3100/ready || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - microservices-net

  alloy:
    image: grafana/alloy:v1.9.0
    container_name: alloy
    command:
      - run
      - --server.http.listen-addr=0.0.0.0:12345
      - --storage.path=/var/lib/alloy
      - /etc/alloy/config.alloy
    ports:
      - "12345:12345"
    volumes:
      - ./alloy/config.alloy:/etc/alloy/config.alloy
      - alloy-data:/var/lib/alloy-data
      - /var/log:/var/log:ro
      - /proc:/host/proc:ro
      - /sys:/sys:ro
      - /:/rootfs:ro
      - /run:/run:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /run/udev/data:/run/udev/data:ro
    depends_on:
      - loki
      - prometheus
    restart: unless-stopped
    networks:
      - microservices-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:12345/ready || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  grafana:
    image: grafana/grafana:12.0.2
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
    volumes:
      - grafana-storage:/var/lib/grafana
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - microservices-net

  node_exporter:
    image: prom/node-exporter:v1.9.1
    container_name: node_exporter
    command: "--path.rootfs=/host"
    pid: host
    restart: unless-stopped
    volumes:
      - /:/host:ro,rslave
    networks:
      - microservices-net

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8300:8080"
    volumes:
      - /:/rootfs:ro
      - /run:/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg
    privileged: true
    restart: unless-stopped
    networks:
      - microservices-net

#  postgres_api_gateway_exporter:
#    image: quay.io/prometheuscommunity/postgres-exporter:v0.15.0
#    container_name: postgres_exporter
#    environment:
#      DATA_SOURCE_NAME: "postgresql://postgres:postgres@postgres:5432/postgres?sslmode=disable"
#    depends_on:
#      - postgres-api-gateway
#    ports:
#      - "9187:9187"
#    networks:
#      - microservices-net

networks:
  microservices-net:
    name: microservices-net
    external: true

volumes:
  alloy-data:
    name: "alloy-data"
    driver: local
  grafana-storage:
    name: "grafana-storage"
    driver: local
  prometheus-data:
    name: "prometheus-data"
    driver: local
  loki-data:
    name: "loki-data"
    driver: local
